/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Staged Changes",
	"Changes",
	"Merge Changes",
	"This file is located outside the current workspace.",
	"M",
	"M",
	"A",
	"D",
	"D",
	"R",
	"C",
	"U",
	"!",
	"D",
	"A",
	"D",
	"A",
	"D",
	"A",
	"M",
	"Modified in index",
	"Modified",
	"Added to index",
	"Deleted in index",
	"Deleted",
	"Renamed in index",
	"Copied in index",
	"Untracked",
	"Ignored",
	"Conflict: both deleted",
	"Conflict: added by us",
	"Conflict: deleted by them",
	"Conflict: added by them",
	"Conflict: deleted by us",
	"Conflict: both added",
	"Conflict: both modified",
	"File {0} in folder {1} has status: {2}, Git",
	"Staged Changes, Git",
	"Changes, Git",
	"Merge, Git"
]);