import { TPromise } from 'vs/base/common/winjs.base';
import { IAction, IActionRunner } from 'vs/base/common/actions';
import { IContextMenuService } from 'vs/platform/contextview/browser/contextView';
import { IMessageService } from 'vs/platform/message/common/message';
import { IInstantiationService } from 'vs/platform/instantiation/common/instantiation';
import { IEditorGroupService } from 'vs/workbench/services/group/common/groupService';
import { IEventService } from 'vs/platform/event/common/event';
import { IConfigurationService } from 'vs/platform/configuration/common/configuration';
import { IKeybindingService } from 'vs/platform/keybinding/common/keybinding';
import { AdaptiveCollapsibleViewletView } from 'vs/workbench/browser/viewlet';
import { ITextFileService } from 'vs/workbench/parts/files/common/files';
import { IUntitledEditorService } from 'vs/workbench/services/untitled/common/untitledEditorService';
export declare class OpenEditorsView extends AdaptiveCollapsibleViewletView {
    private eventService;
    private instantiationService;
    private textFileService;
    private editorGroupService;
    private configurationService;
    private untitledEditorService;
    private static MEMENTO_COLLAPSED;
    private static DEFAULT_VISIBLE_OPEN_EDITORS;
    private static DEFAULT_DYNAMIC_HEIGHT;
    private settings;
    private visibleOpenEditors;
    private dynamicHeight;
    private model;
    private dirtyCountElement;
    private structuralTreeRefreshScheduler;
    private structuralRefreshDelay;
    private groupToRefresh;
    private fullRefreshNeeded;
    constructor(actionRunner: IActionRunner, settings: any, messageService: IMessageService, eventService: IEventService, instantiationService: IInstantiationService, contextMenuService: IContextMenuService, textFileService: ITextFileService, editorGroupService: IEditorGroupService, configurationService: IConfigurationService, keybindingService: IKeybindingService, untitledEditorService: IUntitledEditorService);
    renderHeader(container: HTMLElement): void;
    getActions(): IAction[];
    renderBody(container: HTMLElement): void;
    create(): TPromise<void>;
    private registerListeners();
    private onEditorStacksModelChanged(e);
    private structuralTreeUpdate();
    private highlightActiveEditor();
    private onConfigurationUpdated(configuration);
    private updateDirtyIndicator();
    private getExpandedBodySize(model);
    private static computeExpandedBodySize(model, visibleOpenEditors?, dynamicHeight?);
    setStructuralRefreshDelay(delay: number): void;
    getOptimalWidth(): number;
    shutdown(): void;
}
