/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Editor configuration",
	"Controls the font family.",
	"Controls the font size.",
	"Controls the line height.",
	"Controls visibility of line numbers",
	"Controls visibility of the glyph margin",
	"Columns at which to show vertical rulers",
	"Characters that will be used as word separators when doing word related navigations or operations",
	"The number of spaces a tab is equal to.",
	"Expected 'number'. Note that the value \"auto\" has been replaced by the `editor.detectIndentation` setting.",
	"Insert spaces when pressing Tab.",
	"Expected 'boolean'. Note that the value \"auto\" has been replaced by the `editor.detectIndentation` setting.",
	"When opening a file, `editor.tabSize` and `editor.insertSpaces` will be detected based on the file contents.",
	"Controls if selections have rounded corners",
	"Controls if the editor will scroll beyond the last line",
	"Controls after how many characters the editor will wrap to the next line. Setting this to 0 turns on viewport width wrapping (word wrapping). Setting this to -1 forces the editor to never wrap.",
	"Controls the indentation of wrapped lines. Can be one of 'none', 'same' or 'indent'.",
	"A multiplier to be used on the `deltaX` and `deltaY` of mouse wheel scroll events",
	"Controls if quick suggestions should show up or not while typing",
	"Controls the delay in ms after which quick suggestions will show up",
	"Controls if the editor should automatically close brackets after opening them",
	"Controls if the editor should automatically format the line after typing",
	"Controls if suggestions should automatically show up when typing trigger characters",
	"Controls if suggestions should be accepted 'Enter' - in addition to 'Tab'. Helps to avoid ambiguity between inserting new lines or accepting suggestions.",
	"Controls whether the editor should highlight similar matches to the selection",
	"Controls the number of decorations that can show up at the same position in the overview ruler",
	"Controls the cursor blinking animation, accepted values are 'blink', 'visible', and 'hidden'",
	"Controls the cursor style, accepted values are 'block' and 'line'",
	"Enables font ligatures",
	"Controls if the cursor should be hidden in the overview ruler.",
	"Controls whether the editor should render whitespace characters",
	"Controls whether the editor should render indent guides",
	"Controls if the editor shows reference information for the modes that support it",
	"Controls whether the editor has code folding enabled",
	"Controls if the diff editor shows the diff side by side or inline",
	"Controls if the diff editor shows changes in leading or trailing whitespace as diffs",
	"Controls if the Linux primary clipboard should be supported."
]);