/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Ln {0}, Col {1} ({2} selected)",
	"Ln {0}, Col {1}",
	"{0} selections ({1} characters selected)",
	"{0} selections",
	"LF",
	"CRLF",
	"Tab moves focus",
	"Disable Accessibility Mode",
	"Go to Line",
	"Indentation",
	"Select Encoding",
	"Select End of Line Sequence",
	"Select Language Mode",
	"Spaces: {0}",
	"Tab Size: {0}",
	"Change Language Mode",
	"No text editor active at this time",
	"Configured Language",
	"languages",
	"Configure File Associations...",
	"Configure File Association for '{0}'...",
	"Auto Detect",
	"Select Language Mode",
	"You can configure filename to language associations in the **files.associations** section. The changes may need a restart to take effect on already opened files.",
	"Change Indentation",
	"No text editor active at this time",
	"The active code editor is read-only.",
	"change view",
	"convert file",
	"Select Action",
	"Change End of Line Sequence",
	"No text editor active at this time",
	"The active code editor is read-only.",
	"Select End of Line Sequence",
	"Change File Encoding",
	"No text editor active at this time",
	"No file active at this time",
	"Save with Encoding",
	"Reopen with Encoding",
	"Select Action",
	"Select File Encoding to Reopen File",
	"Select File Encoding to Save with"
]);