/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	"Retry",
	"Rename",
	"Rename",
	"File '{0}' is currently being saved, please try again later.",
	"New File",
	"New Folder",
	"New File",
	"New Folder",
	"New File",
	"New Folder",
	"Are you sure you want to delete '{0}' and its contents?",
	"Are you sure you want to delete '{0}'?",
	"You can restore from the recycle bin.",
	"You can restore from the trash.",
	"&&Move to Recycle Bin",
	"&&Move to Trash",
	"Are you sure you want to permanently delete '{0}' and its contents?",
	"Are you sure you want to permanently delete '{0}'?",
	"This action is irreversible!",
	"&&Delete",
	"Delete Permanently",
	"Delete",
	"Delete",
	"Import Files",
	"A file or folder with the same name already exists in the destination folder. Do you want to replace it?",
	"This action is irreversible!",
	"&&Replace",
	"Copy",
	"Paste",
	"Duplicate",
	"Open to the Side",
	"Select for Compare",
	"Compare Active File With...",
	"The selected file can not be compared with '{0}'.",
	"Open a file first to compare it with another file.",
	"Compare with '{0}'",
	"Compare Files",
	"Refresh",
	"Save",
	"Save As...",
	"Save All",
	"Save Dirty Files",
	"Revert File",
	"Close All Files",
	"Close File",
	"Close Other Files",
	"Close File",
	"There is currently no file opened to close.",
	"Close Other Files",
	"Close All Files",
	"Open Next Working File",
	"Currently there are no working files.",
	"Open Previous Working File",
	"Currently there are no working files.",
	"Add Active File to Working Files",
	"Open a file first to add it to working files",
	"Focus on Working Files",
	"Focus on Files Explorer",
	"Show Active File in Explorer",
	"Open a file first to show it in the explorer",
	"A file or folder name must be provided.",
	"A file or folder **{0}** already exists at this location. Please choose a different name.",
	"The name **{0}** is not valid as a file or folder name. Please choose a different name.",
	"The name **{0}** results in a path that is too long. Please choose a shorter name."
]);