/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'openChange',
	'openFile',
	'init',
	'refresh',
	'stageChanges',
	'stageAllChanges',
	'confirmUndoMessage',
	'confirmUndoAllOne',
	'confirmUndoAllMultiple',
	{ key: 'cleanChangesLabel', comment: ['&& denotes a mnemonic'] },
	'confirmUndo',
	'irreversible',
	{ key: 'cleanChangesLabel', comment: ['&& denotes a mnemonic'] },
	'undoChanges',
	'undoAllChanges',
	'unstage',
	'unstageAllChanges',
	'dirtyTreeCheckout',
	'branch',
	'commitStaged',
	'commit',
	'commitAll',
	'commitAll2',
	'commitStaged2',
	'pull',
	'dirtyTreePull',
	'authFailed',
	'pullWithRebase',
	'push',
	'authFailed',
	'publish',
	'confirmPublishMessage',
	{ key: 'confirmPublishMessageButton', comment: ['&& denotes a mnemonic'] },
	'publishPickMessage',
	'authFailed',
	'authFailed',
	'sync',
	'sync',
	'synchronizing',
	'currentlyDetached',
	'noUpstream',
	'currentBranch',
	'dirtyChanges',
	'currentBranchSingle',
	'currentBranchSinglePlural',
	'currentBranchPluralSingle',
	'currentBranchPlural',
	'undoLastCommit',
	'checkout',
	'branch2'
]);