/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
define([], [
	'Run Build Task',
	'Run Test Task',
	'Run Rebuild Task',
	'Run Clean Task',
	'Configure Task Runner',
	'Tasks are only available on a workspace folder.',
	'Select a Task Runner',
	'Auto detecting tasks for {0}',
	'Auto detecting the task system failed. Using default template. Consult the task output for details.',
	"Unable to create the 'tasks.json' file inside the '.vscode' folder. Consult the task output for details.",
	'Close',
	'Terminate Running Task',
	'Failed to terminate running task',
	'Show Task Log',
	"Run Task",
	"99+",
	"Tasks",
	'Error: The content of the tasks.json file has syntax errors. Please correct them before executing a task.\n',
	'No task runner configured.',
	"No valid task runner configured. Supported task runners are 'service' and 'program'.",
	'There is an active running task right now. Terminate it first before executing another task.',
	'There is a task running. Do you want to terminate it?',
	"&&Terminate Task",
	'An error has occurred while running a task. See task log for details.',
	"Tasks",
	"Run Task",
	'The regular expression to find an error, warning or info in the output.',
	'The match group index of the filename. If omitted 1 is used.',
	'The match group index of the problem\'s location. Valid location patterns are: (line), (line,column) and (startLine,startColumn,endLine,endColumn). If omitted line and column is assumed.',
	'The match group index of the problem\'s line. Defaults to 2',
	'The match group index of the problem\'s column. Defaults to 3',
	'The match group index of the problem\'s end line. Defaults to undefined',
	'The match group index of the problem\'s end column. Defaults to undefined',
	'The match group index of the problem\'s severity. Defaults to undefined',
	'The match group index of the problem\'s code. Defaults to undefined',
	'The match group index of the message. If omitted it defaults to 4 if location is specified. Otherwise it defaults to 5.',
	'In a multi line matcher loop indicated whether this pattern is executed in a loop as long as it matches. Can only specified on a last pattern in a multi line pattern.',
	'The regular expression to detect the begin or end of a watching task.',
	'The match group index of the filename. Can be omitted.',
	'The name of a base problem matcher to use.',
	'The owner of the problem inside Code. Can be omitted if base is specified. Defaults to \'external\' if omitted and base is not specified.',
	'The default severity for captures problems. Is used if the pattern doesn\'t define a match group for severity.',
	'Controls if a problem reported on a text document is applied only to open, closed or all documents.',
	'A problem pattern or the name of a predefined problem pattern. Can be omitted if base is specified.',
	'Defines how file names reported in a problem pattern should be interpreted.',
	'If set to true the watcher is in active mode when the task starts. This is equals of issuing a line that matches the beginPattern',
	'If matched in the output the start of a watching task is signaled.',
	'If matched in the output the end of a watching task is signaled.',
	'A regular expression signaling that a watched tasks begins executing triggered through file watching.',
	'A regular expression signaling that a watched tasks ends executing.',
	'The command to be executed. Can be an external program or a shell command.',
	'Specifies whether the command is a shell command or an external program. Defaults to false if omitted.',
	'Additional arguments passed to the command.',
	'Additional command options',
	'The current working directory of the executed program or script. If omitted Code\'s current workspace root is used.',
	'The environment of the executed program or shell. If omitted the parent process\' environment is used.',
	'Controls whether the output of the running task is shown or not. If omitted \'always\' is used.',
	'Whether the executed task is kept alive and is watching the file system.',
	'Whether the user is prompted when VS Code closes with a running background task.',
	'Controls whether the executed command is echoed to the output. Default is false.',
	'Controls whether the task name is added as an argument to the command. Default is false.',
	'Prefix to indicate that an argument is task.',
	'The problem matcher(s) to use. Can either be a string or a problem matcher definition or an array of strings and problem matchers.',
	'The task configurations. Usually these are enrichments of task already defined in the external task runner.',
	"The task's name",
	'Additional arguments passed to the command when this task is invoked.',
	'Controls whether the task name is added as an argument to the command. If omitted the globally defined value is used.',
	'Controls whether the output of the running task is shown or not. If omitted the globally defined value is used.',
	'Controls whether the executed command is echoed to the output. Default is false.',
	'Whether the executed task is kept alive and is watching the file system.',
	'Maps this task to Code\'s default build command.',
	'Maps this task to Code\'s default test command.',
	'The problem matcher(s) to use. Can either be a string or a problem matcher definition or an array of strings and problem matchers.',
	'The config\'s version number',
	'Windows specific build configuration',
	'Mac specific build configuration',
	'Linux specific build configuration'
]);