import { TPromise } from 'vs/base/common/winjs.base';
import uri from 'vs/base/common/uri';
import { IFileService, IResolveFileOptions, IFileStat, IContent, IStreamContent, IImportResult, IResolveContentOptions, IUpdateContentOptions } from 'vs/platform/files/common/files';
import { IConfigurationService } from 'vs/platform/configuration/common/configuration';
import { IEventService } from 'vs/platform/event/common/event';
import { IWorkspaceContextService } from 'vs/platform/workspace/common/workspace';
import { IMessageService } from 'vs/platform/message/common/message';
export declare class FileService implements IFileService {
    private configurationService;
    private eventService;
    private contextService;
    private messageService;
    _serviceBrand: any;
    private raw;
    private configurationChangeListenerUnbind;
    constructor(configurationService: IConfigurationService, eventService: IEventService, contextService: IWorkspaceContextService, messageService: IMessageService);
    private onFileServiceError(msg);
    private registerListeners();
    private onConfigurationChange(configuration);
    updateOptions(options: any): void;
    resolveFile(resource: uri, options?: IResolveFileOptions): TPromise<IFileStat>;
    existsFile(resource: uri): TPromise<boolean>;
    resolveContent(resource: uri, options?: IResolveContentOptions): TPromise<IContent>;
    resolveStreamContent(resource: uri, options?: IResolveContentOptions): TPromise<IStreamContent>;
    resolveContents(resources: uri[]): TPromise<IContent[]>;
    updateContent(resource: uri, value: string, options?: IUpdateContentOptions): TPromise<IFileStat>;
    moveFile(source: uri, target: uri, overwrite?: boolean): TPromise<IFileStat>;
    copyFile(source: uri, target: uri, overwrite?: boolean): TPromise<IFileStat>;
    createFile(resource: uri, content?: string): TPromise<IFileStat>;
    createFolder(resource: uri): TPromise<IFileStat>;
    rename(resource: uri, newName: string): TPromise<IFileStat>;
    del(resource: uri, useTrash?: boolean): TPromise<void>;
    private doMoveItemToTrash(resource);
    importFile(source: uri, targetFolder: uri): TPromise<IImportResult>;
    watchFileChanges(resource: uri): void;
    unwatchFileChanges(resource: uri): void;
    unwatchFileChanges(path: string): void;
    dispose(): void;
}
