import { TPromise } from 'vs/base/common/winjs.base';
import editorbrowser = require('vs/editor/browser/editorBrowser');
import editorcommon = require('vs/editor/common/editorCommon');
import debug = require('vs/workbench/parts/debug/common/debug');
import { IWorkspaceContextService } from 'vs/workbench/services/workspace/common/contextService';
import { IInstantiationService } from 'vs/platform/instantiation/common/instantiation';
import { IContextMenuService } from 'vs/platform/contextview/browser/contextView';
import { Range } from 'vs/editor/common/core/range';
export declare class DebugEditorContribution implements debug.IDebugEditorContribution {
    private editor;
    private debugService;
    private contextService;
    private contextMenuService;
    private instantiationService;
    private toDispose;
    private breakpointHintDecoration;
    private hoverWidget;
    private showHoverScheduler;
    private hideHoverScheduler;
    private hoverRange;
    private hoveringOver;
    static getDebugEditorContribution(editor: editorcommon.ICommonCodeEditor): DebugEditorContribution;
    constructor(editor: editorbrowser.ICodeEditor, debugService: debug.IDebugService, contextService: IWorkspaceContextService, contextMenuService: IContextMenuService, instantiationService: IInstantiationService);
    private getContextMenuActions(breakpoint, uri, lineNumber);
    private registerListeners();
    getId(): string;
    showHover(range: Range, hoveringOver: string, focus: boolean): TPromise<void>;
    private ensureBreakpointHintDecoration(showBreakpointHintAtLineNumber);
    private onDebugStateUpdate(state);
    private hideHoverWidget();
    private onEditorMouseDown(mouseEvent);
    private onEditorMouseMove(mouseEvent);
    private onKeyDown(e);
    private static BREAKPOINT_HELPER_DECORATION;
    dispose(): void;
}
