import { TPromise } from 'vs/base/common/winjs.base';
import editorbrowser = require('vs/editor/browser/editorBrowser');
import { IInstantiationService } from 'vs/platform/instantiation/common/instantiation';
import debug = require('vs/workbench/parts/debug/common/debug');
import { Range } from 'vs/editor/common/core/range';
export declare class DebugHoverWidget implements editorbrowser.IContentWidget {
    private editor;
    private debugService;
    private instantiationService;
    static ID: string;
    allowEditorOverflow: boolean;
    private domNode;
    isVisible: boolean;
    private tree;
    private showAtPosition;
    private highlightDecorations;
    private complexValueContainer;
    private treeContainer;
    private complexValueTitle;
    private valueContainer;
    private stoleFocus;
    private toDispose;
    constructor(editor: editorbrowser.ICodeEditor, debugService: debug.IDebugService, instantiationService: IInstantiationService);
    private registerListeners();
    getId(): string;
    getDomNode(): HTMLElement;
    showAt(range: Range, hoveringOver: string, focus: boolean): TPromise<void>;
    private getExpression(namesToFind);
    private doShow(position, expression, focus, forceValueHover?);
    private layoutTree();
    hide(): void;
    getPosition(): editorbrowser.IContentWidgetPosition;
    dispose(): void;
}
